server:
 port: 9091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ai_test?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
#deepseek
langchain4j:
  open-ai:
    chat-model:
      api-key: xxxxx
      base-url: https://api.deepseek.com/v1
      model-name: deepseek-reasoner
      log-requests: true
      log-responses: true
  community:
    dashscope:
      chat-model:
        api-key: xxxxx
        model-name: qwen-max
      embedding-model:
        api-key: xxxx
        model-name: text-embedding-v3
      streaming-chat-model:
        api-key: xxxxxx
        model-name: qwen-plus
